name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.2.0



