name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Setup Latest Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: 4.4.1
          cache: false
      runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn



